ALTER TABLE rimfirede.ASSESSMENTS ADD
  CONSTRAINT ASSESSMENTS_SYSTEMID$FK
      FOREIGN KEY (SYSTEM_ID)
          REFERENCES rimfirede.SYSTEMS (SYSTEM_ID)
              ;
ALTER TABLE rimfirede.ASSESSMENTS ADD
    CONSTRAINT ASSESSMENTS_HIERARCHYID$FK
        FOREIGN KEY (ASSESSMENT_HIERARCHY_ID)
            REFERENCES rimfirede.HIERARCHIES (HIERARCHY_ID)
;