ALTER TABLE rimfirede.COMPOSITIONS ADD
        CONSTRAINT COMPOSITIONS_ASSESSID$FK
        FOREIGN KEY (ASSESSMENT_ID)
            REFERENCES rimfirede.ASSESSMENTS (ASSESSMENT_ID)
;
ALTER TABLE rimfirede.COMPOSITIONS ADD
    CONSTRAINT COMPOSITIONS_SYSTEMID$FK
        FOREIGN KEY (SYSTEM_ID)
            REFERENCES rimfirede.SYSTEMS (SYSTEM_ID)
;
ALTER TABLE rimfirede.COMPOSITIONS ADD
    CONSTRAINT COMPOSITIONS_HIERID$FK
        FOREIGN KEY (HIERARCHY_ID)
            REFERENCES rimfirede.HIERARCHIES (HIERARCHY_ID)
;
ALTER TABLE rimfirede.COMPOSITIONS ADD
    CONSTRAINT COMPOSITIONS_PARTID$FK
        FOREIGN KEY (PART_ID)
            REFERENCES rimfirede.PARTS (PART_ID)
;