ALTER TABLE rimfirede.COMPOSITIONS ADD
  CONSTRAINT COMPOSITIONS_ROWSTATIND$CK
  CHECK (ROW_STATUS_IND IN ('A', 'I'))
;

ALTER TABLE rimfirede.COMPOSITIONS ADD
    CONSTRAINT LEVEL_NUM$CK
  CHECK (LEVEL_NUM <> 0)
;