ALTER TABLE rimfirede.MEDIA ADD
    CONSTRAINT MEDIA_ASSESSMENTID$FK
        FOREIGN KEY (ASSESSMENT_ID)
            REFERENCES rimfirede.ASSESSMENTS (ASSESSMENT_ID)
                ON DELETE CASCADE
;
ALTER TABLE rimfirede.MEDIA ADD
  CONSTRAINT MEDIA_TYPEID$FK
        FOREIGN KEY (MEDIA_TYPE_ID)
            REFERENCES rimfirede.VT_MEDIA_TYPES (MEDIA_TYPE_ID)
;
