ALTER TABLE rimfirede.PARTS ADD
  CONSTRAINT PARTS_ROWSTATIND$CK
  CHECK (ROW_STATUS_IND IN ('A', 'I', 'D'))
  ;
ALTER TABLE rimfirede.PARTS ADD
    CONSTRAINT HIERID_PARTNBR_UIX
    UNIQUE USING INDEX hierid_partnbr_uix
;