ALTER TABLE rimfirede.SYSTEMS ADD
  CONSTRAINT SYSTEMS_DEFAULT_IND_YN$CK
  CHECK (DEFAULT_IND IN ('N','Y'))
;
ALTER TABLE rimfirede.SYSTEMS ADD
CONSTRAINT SYSTEM_STAT$CK
  CHECK (STATUS_IND in('A','I','D'))
;