ALTER TABLE rimfirede.XR_SYSTEM_RECORDINGTYPE ADD
    CONSTRAINT XR_SYSTEM_RECORDING_SYSID$FK
        FOREIGN KEY (SYSTEM_ID)
            REFERENCES rimfirede.SYSTEMS (SYSTEM_ID);
ALTER TABLE rimfirede.XR_SYSTEM_RECORDINGTYPE
    ADD CONSTRAINT XR_SYSTEM_RECORDING_RTID$FK
        FOREIGN KEY (RECORDING_TYPE_ID)
            REFERENCES rimfirede.VT_RECORDING_TYPES (RECORDING_TYPE_ID)
                ;